name: Run License Tests
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - dev
jobs:
  license_tests:
    uses: openvoiceos/.github/.github/workflows/license_tests.yml@feat/shared_actions1
